#server:
#  port: 8080
#
#spring:
#  profiles:
#    active: db
#
#  datasource:
#    url: ${NEON_DB_URL}
#    driver-class-name: org.postgresql.Driver
#    username: ${NEON_DB_USERNAME}
#    password: ${NEON_DB_PASSWORD}
#
#  h2:
#    console:
#      enabled: true
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#  sql:
#    init:
#      platform: postgresql
